spring:
  application:
    name: springfox-swagger
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/task?characterEncoding=utf-8&serverTimezone=GMT%2B8



server:
  port: 8088


swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0
  try-host: http://localhost:${server.port}

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.login.demo.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
